[package]
name = "rs2ts-proc"
version = "0.1.0"
authors = ["Jalmari Ikävalko <tzaeru@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
rs2ts = { path = "../" }

[dependencies.syn]
version = "1.0.13"
features = ["extra-traits"]